name: Build & publish Docker image
on:
  workflow_dispatch:
env:
  DOCKERHUB_USERNAME: jaxvanyang
jobs:
  prepare:
    name: Get the latest RootFS release number
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.get-release.outputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get-release
        run: echo "release=$(make release_num)" >> "${GITHUB_OUTPUT}"
  build:
    name: Build & publish Docker image
    runs-on: ubuntu-latest
    needs: prepare
    env:
      RELEASE: ${{ needs.prepare.outputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare RootFS tar
        run: make tar "RELEASE=$RELEASE"
      - name: Build & push release Docker image
        run: |
          make docker_image "USER=$DOCKERHUB_USERNAME" "RELEASE=$RELEASE"
          docker push "$DOCKERHUB_USERNAME/archriscv:$RELEASE"
      - name: Build & push latest Docker image
        run: |
          docker buildx build \
            -f latest.dockerfile \
            -t "$DOCKERHUB_USERNAME/archriscv:latest" \
            --push \
            --platform linux/riscv64 \
            --build-arg "USER=$DOCKERHUB_USERNAME" \
            --build-arg "RELEASE=$RELEASE" \
            .
